services:
  composer:
    build:
      dockerfile: .docker/php${PHP_VERSION:-8.2}/Dockerfile
    environment:
      COMPOSER_CACHE_DIR: /app/.cache/composer
    volumes:
      - .:/app
    entrypoint: composer

  phpunit:
    build:
      dockerfile: .docker/php${PHP_VERSION:-8.2}/Dockerfile
    volumes:
      - .:/app
    entrypoint: vendor/bin/phpunit

  php-cs-fixer:
    image: ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.3
    volumes:
      - .:/code
