name: PHP CS Fixer

on: [ push, pull_request ]

jobs:
  test:
    name: Run PHP CS Fixer

    runs-on: ubuntu-latest

    env:
      PHP_VERSION: 7.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        uses: docker://ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.3
        with:
          args: check
