name: PHPUnit

on:
  - pull_request
  - push

jobs:
  test:
    strategy:
      matrix:
        include:
          - image: php:7.2-cli-alpine
            dependencies: laravel/framework:^7.0
            prefer_lowest: 1

          - image: php:7.3-cli-alpine
            dependencies: laravel/framework:^8.0
            prefer_lowest: 1

          - image: php:8.0-cli-alpine
            dependencies: laravel/framework:^9.0
            prefer_lowest: 1

          - image: php:8.1-cli-alpine
            dependencies: laravel/framework:^10.0
            prefer_lowest: 1

          - image: php:8.2-cli-alpine
            dependencies: laravel/framework:^11.0
            prefer_lowest: 1

    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.image }}
      env:
        COMPOSER_PREFER_STABLE: 1
        COMPOSER_PREFER_LOWEST: ${{ matrix.prefer_lowest }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Specify Composer dependencies
        run: composer require ${{ matrix.dependencies }} --no-update --no-interaction --no-progress

      - name: Update Composer dependencies
        run: composer update --no-interaction --no-progress

      - name: Run PHPUnit
        run: vendor/bin/phpunit

  coverage:
    name: Analyze code coverage

    runs-on: ubuntu-latest

    env:
      PHP_VERSION: 7.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build containers
        run: docker compose build

      - name: Install Composer dependencies
        run: docker compose run composer update --no-interaction --no-progress

      - name: Run PHPUnit with a coverage analysis
        run: docker compose run phpunit --coverage-clover coverage.xml

      - name: Upload the coverage report
        uses: codecov/codecov-action@v3
