name: Run tests

on: [ push, pull_request ]

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ 'ubuntu-latest' ]
                php: [ '7.2' ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Install dependencies
                run: composer install

            -   name: Run tests
                run: vendor/bin/phpunit
